#!/usr/bin/env bash
# build-claude-ai-pack.sh: builds one-file data packs for participants who use
# claude.ai instead of Claude Code. One file is easier to upload or paste than
# sixteen.
#
# Usage: bash scripts/build-claude-ai-pack.sh
# Output:
#   demos/01-ceos-morning/claude-ai-pack.md    company profile, calendar, 14 e-mails
#   demos/02-chief-of-staff/claude-ai-pack.md  company profile, trust levels, 3 meeting notes
#
# Run it again after changing any of the source files.

set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# build_pack OUTPUT TITLE SOURCE...
build_pack() {
  local output="$1" title="$2" source
  shift 2
  {
    printf '# %s\n\n' "$title"
    printf 'Data pack for claude.ai. Sotarena S.L. and every person in it are fictional.\n\n'
    printf 'Upload or paste this whole file into a new chat, then add a prompt from claude-ai-version.md.\n\n'
    printf 'Generated by scripts/build-claude-ai-pack.sh. Do not edit by hand.\n\n'
    printf 'Files in this pack:\n\n'
    for source in "$@"; do
      printf -- '- %s\n' "${source#"$REPO"/}"
    done
    for source in "$@"; do
      printf '\n\n<<<<< FILE: %s >>>>>\n\n' "${source#"$REPO"/}"
      cat "$source"
    done
    printf '\n<<<<< END OF PACK >>>>>\n'
  } >"$output"
  printf 'Wrote %s\n' "${output#"$REPO"/}"
}

build_pack "$REPO/demos/01-ceos-morning/claude-ai-pack.md" \
  "Demo 1 data pack: the CEO's morning" \
  "$REPO/company/COMPANY.md" \
  "$REPO/demos/01-ceos-morning/calendar/2026-09-21.md" \
  "$REPO"/demos/01-ceos-morning/inbox/E*.md

build_pack "$REPO/demos/02-chief-of-staff/claude-ai-pack.md" \
  "Demo 2 data pack: chief of staff with trust levels" \
  "$REPO/company/COMPANY.md" \
  "$REPO/demos/02-chief-of-staff/TRUST-LEVELS.md" \
  "$REPO"/demos/02-chief-of-staff/notes/M*.md
